- name: ollama_chat/agro-coder
  edit_format: whole
  use_repo_map: false
  extra_params:
    num_ctx: 16384

- name: ollama_chat/deepseek-coder-v2:16b
  edit_format: whole
  use_repo_map: false
  extra_params:
    num_ctx: 16384